//
//  main.c
//  Issue002
//
//  Created by Scorpio on 4/8/15.
//  Copyright (c) 2015 Oohcar. All rights reserved.
//

/**
 *  Problem 002 < Even Fibonacci numbers >
 *
 *  Content :
 *
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 *  By starting with 1 and 2, the first 10 terms will be:
 
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 *  find the sum of the even-valued terms.
 *
 */
#include <stdio.h>
#include <time.h>
#include <math.h>

//创建斐波那契数列的方法.
int Fib(int index)
{
    
    if(index < 1)
    {
        return -1;
    }
    
    if(index == 1 || index == 2)
    {
        return 1;
    }
    
    return Fib(index - 1) + Fib(index - 2);
    
}

int FibPro(int n)
{
    double gh5 = sqrt((double)5);
    return (pow((1+gh5),n)-pow((1-gh5),n))/(pow((double)2,n)*gh5);
}

//计算小于4百万的偶数斐波那契数列的和.
long sumForFibEven(int limit)
{
    long sum = 0;
    
    int i = 0;
    
    while (FibPro(i) < limit) {
        long tmp = FibPro(i);
        if (tmp % 2 == 0) {
            sum += tmp;
        }
        i ++;
    }
    
    return sum;
}

long sumForFibEvenPro(int limit)
{
    long sum = 0;
    
    int i = 0;
    
    while (FibPro(i) < limit) {
        sum += FibPro(i);
        i = i + 3;
    }
    
    return sum;

}

/**
 * 斐波那契数列的特点 : 
 * 
 * odd,odd,even,odd,odd,even,odd,odd,even ...
 * 
 * 每第3个数必定是偶数 
 * 
 * Sum = x + y, 3x + 5y, ...
 *
 */
long sumForFibEvenProEx(int limit)
{
    long sum = 0;
    long x = 1;
    long y = 1;

    while (sum < limit) {
        sum = sum + (x + y);
        long tmp = x;
        x = x + 2 * y;
        y = 2 * tmp + 3 * y;
    }
    
    return sum;
}


int main(int argc, const char * argv[]) {
    
    int limit = 4000000;
    
    clock_t start, end;
    double time;
    
    start = clock();
    printf("Sum is < %ld > \n",sumForFibEven(limit));
    end = clock();
    time = (double)(end - start)/CLOCKS_PER_SEC;
    printf("Time < %f > \n",time);
    start = clock();
    printf("Sum is < %ld > \n",sumForFibEvenPro(limit));
    end = clock();
    time = (double)(end - start)/CLOCKS_PER_SEC;
    printf("Time < %f > \n",time);
    start = clock();
    printf("Sum is < %ld > \n",sumForFibEvenProEx(limit));
    end = clock();
    time = (double)(end - start)/CLOCKS_PER_SEC;
    printf("Time < %f > \n",time);

    return 0;
}
